# Generated by Django 4.2.1 on 2023-07-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("krishi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="selling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="sellimg")),
                ("product", models.CharField(max_length=100)),
                ("productdet", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("phone", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        
    ]
