# Generated by Django 4.2.1 on 2023-10-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("krishi", "0002_selling_delete_seller"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="detection")),
            ],
        ),
        migrations.AddField(
            model_name="selling",
            name="username",
            field=models.CharField(default="unknown", max_length=100),
        ),
    ]
