# Generated by Django 4.2.1 on 2023-10-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("krishi", "0003_uploadedimage_selling_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="counsel",
            name="last_name",
        ),
    ]
