# Generated by Django 4.2.1 on 2023-11-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("krishi", "0004_remove_counsel_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="counsel",
            name="type",
            field=models.CharField(default="soil test", max_length=100),
        ),
    ]
