# Generated by Django 4.2.1 on 2023-11-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("krishi", "0007_plantresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantresult",
            name="message",
        ),
        migrations.AddField(
            model_name="plantresult",
            name="life_cycle",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="plantresult",
            name="prevention_and_control",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="plantresult",
            name="symptoms",
            field=models.TextField(default=None),
        ),
    ]
