# Generated by Django 4.2.1 on 2023-11-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("krishi", "0008_remove_plantresult_message_plantresult_life_cycle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantresult",
            name="cause",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="plantresult",
            name="name2",
            field=models.CharField(default="not available", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="counsel",
            name="type",
            field=models.CharField(default="general counselling", max_length=100),
        ),
    ]
