# Generated by Django 4.2.1 on 2023-11-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("krishi", "0009_plantresult_cause_plantresult_name2_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="seller",
        ),
        migrations.AlterField(
            model_name="counsel",
            name="date",
            field=models.DateField(default="2023-04-01"),
        ),
    ]
