# Generated by Django 4.2.1 on 2024-02-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("krishi", "0010_delete_seller_alter_counsel_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[("Government", "Government"), ("Private", "Private")],
                        max_length=50,
                    ),
                ),
                ("policy_name", models.CharField(max_length=100)),
            ],
        ),
    ]
