# Generated by Django 4.2.1 on 2024-02-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("krishi", "0011_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="policy_content",
            field=models.TextField(default="Not Available"),
        ),
        migrations.AddField(
            model_name="policy",
            name="policy_link",
            field=models.TextField(default="Not Available"),
        ),
    ]
